### ISSUE TITLE
godot-3.5.3-yandex-ads

### ISSUE THREAD

**Issue by disanapa** [noctisalamandra/godot-yandex-ads-android#10]
Добрый вечер. Под godot-3.5.2-yandex-ads будет? SDK 33.

**Comment by Leonavichus** [comment]
Надеюсь найду время и сделаю

**Comment by disanapa** [comment]
Спасибо, подождем.

**Comment by disanapa** [comment]
Привет, все так плохо?

**Comment by Leonavichus** [comment]
Привет, плагин готов. Но до портирования в godot никак руки не дойдут.

**Comment by Leonavichus** [comment]
Думаю в мае выложу новую версию.
