### ISSUE TITLE
Ошибка при экспорте

### ISSUE THREAD

**Issue by danila-nachinalov** [noctisalamandra/godot-yandex-ads-android#11]
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\User\YandexDisk-akkaunt.danila5\Projects\Godot\Godot 3\Tappy Plane v2\android\build\build.gradle' line: 32

* What went wrong:
Could not compile build file 'C:\Users\User\YandexDisk-akkaunt.danila5\Projects\Godot\Godot 3\Tappy Plane v2\android\build\build.gradle'.
> startup failed:
  build file 'C:\Users\User\YandexDisk-akkaunt.danila5\Projects\Godot\Godot 3\Tappy Plane v2\android\build\build.gradle': 32: only buildscript {}, pluginManagement {} and other plugins {} script blocks are allowed before plugins {} blocks, no other statements are allowed
  
  See https://docs.gradle.org/7.4/userguide/plugins.html#sec:plugins_block for information on the plugins {} block
  
   @ line 32, column 1.
     plugins {
     ^
  
  1 error

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s

Exit Code: 1

**Comment by Leonavichus** [comment]
Я знаю об ошибке, я сейчас полностью переписываю плагин, так как яндекс обновили весь код в новой версии ads (6.0). Я думаю мне еще понадобится где-то неделя чтобы выложить новую версию.

**Comment by Leonavichus** [comment]
Хотя ваша ошибка, наверное, не с этим связана. Можете сказать какую версию Godot вы используете?

**Comment by danila-nachinalov** [comment]
> Хотя ваша ошибка, наверное, не с этим связана. Можете сказать какую версию Godot вы используете?

3.5.2

**Comment by Leonavichus** [comment]
Тогда должно быть все нормально. Можете описать все действия настройки плагина или если вам удобно можем в Discord всё обсудить.

**Comment by danila-nachinalov** [comment]
> Тогда должно быть все нормально. Можете описать все действия настройки плагина или если вам удобно можем в Discord всё обсудить.

Спасибо, уже не надо.
