### ISSUE TITLE
Как протестировать?

### ISSUE THREAD

**Issue by mir0lub** [noctisalamandra/godot-yandex-ads-android#12]
Хотел протестить межстраничную рекламу, но при экспорте в режиме отладки вообще ничего не отображается.. ли так должно быть?
И как понять что реклама грузится, как разрешения нужно включить?

**Comment by Leonavichus** [comment]
Здравствуйте, пока никак. Я в данный момент переписываю плагин, так как яндекс поменял код sdk.

**Comment by mir0lub** [comment]
Ок, буду ждать обнову :)

**Comment by code-with-max** [comment]
Godot тоже поменял :(
