### ISSUE TITLE
Доступность на Godot4

### ISSUE THREAD

**Issue by GromovProd** [noctisalamandra/godot-yandex-ads-android#13]
Добрый день!
Пробовал запустить межстраничную рекламу или rewarded на godot 4.1, но не увидел рекламы.
Правильно понимаю, что сейчас плагин поддерживает только баннеры?

**Comment by Leonavichus** [comment]
Пока что да, на праздниках постараюсь исправить все.

**Comment by JerakRus** [comment]
Привет, а подскажи будешь сразу для godot 4.2 версии исправлять ? (смотрю по коммитам там уже что-то с 4.2  stable есть) или пока для 4.1 ? Спрашиваю потому что судя по доке годо 4.2 полностью поменяли способ подключения плагинов, и плагины для 4.1 и 4.2 не совместимы между собой. Заранее благодарю за ответ!

**Comment by Leonavichus** [comment]
> Привет, а подскажи будешь сразу для godot 4.2 версии исправлять ? (смотрю по коммитам там уже что-то с 4.2  stable есть) или пока для 4.1 ? Спрашиваю потому что судя по доке годо 4.2 полностью поменяли способ подключения плагинов, и плагины для 4.1 и 4.2 не совместимы между собой. Заранее благодарю за ответ!

Скорее всего буду сразу исправлять для 4.2. Если время останется сделаю для 4.1 и 3.5.

**Comment by disanapa** [comment]
Добрый день, работа ведётся?

**Comment by Leonavichus** [comment]
Ведётся по мере возможности.
