### ISSUE TITLE
4.2.2

### ISSUE THREAD

**Issue by disanapa** [noctisalamandra/godot-yandex-ads-android#16]
![image](https://github.com/user-attachments/assets/927323a2-fa43-41c2-aad7-6a4586f18bf6)
Такая ошибка вылетает. Новый пустой проект.

**Comment by Leonavichus** [comment]
[Пример проекта](https://github.com/noctisalamandra/godot-yandex-ads-android-demo). Убедитесь все ли правильно настроили, так как у меня и у других тестеров все работает нормально.

**Comment by disanapa** [comment]
Причина в самом движке, буду разбираться, не билдится, можно закрывать. Спасибо.
