### ISSUE TITLE
Проблема с загрузкой игры с подключенным плагином на 4.2.2 при тестировании на стареньком Xiaomi на Android 10

### ISSUE THREAD

**Issue by DNAGamesGit** [noctisalamandra/godot-yandex-ads-android#18]
Привет!
Прошу подсказать - пытаюсь запустить игру с подключенным по инструкции плагином, но сразу же после лого godot происзодит вылет. Пробовал и со скриптом на сцене, и без, разницы нет.
Через adb logcat выгрузил логи, прикрепляю скриншот

Судя по всему, не может найти какие-то связанные с interstitial ads пути или что-то такое.

Ты случайно не знаешь, в чем может быть дело? Другие плагины типо Firebase/Rateme работают отлично.

Спасибо заранее!
![Uploading Screenshot_1.png…]()

**Comment by DNAGamesGit** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/3ef40b50-4050-4ee1-9f13-00f442ddd6de)

**Comment by DNAGamesGit** [comment]
При этом ваша демо версия работает на моем телефоне. =( на 4.3

**Comment by DNAGamesGit** [comment]
Так, я починил спустя долгие часы поисков.. игра запустилась, баннер - показывает. помогло добавление _get_android_dependencies(platform, debug) в файл export_plugin в файлы аддона 4.2.2., тк там их не было. а в демо версии эта функция есть!


![image](https://github.com/user-attachments/assets/13806977-eb69-4811-be1d-9e45d4a9f6a8)

**Comment by DNAGamesGit** [comment]
@Leonavichus Прошу подсказать еще
https://ads.yandex.com/helpcenter/ru/dev/android/gdpr у яндекс медиации есть такое требование
Нету ли в этом плагине функционала для запуска такого окна?

**Comment by Leonavichus** [comment]
> @Leonavichus Прошу подсказать еще https://ads.yandex.com/helpcenter/ru/dev/android/gdpr у яндекс медиации есть такое требование Нету ли в этом плагине функционала для запуска такого окна?

Здравствуйте, такого функционала в плагине нет.

**Comment by Leonavichus** [comment]
> Так, я починил спустя долгие часы поисков.. игра запустилась, баннер - показывает. помогло добавление _get_android_dependencies(platform, debug) в файл export_plugin в файлы аддона 4.2.2., тк там их не было. а в демо версии эта функция есть!
> 
> ![image](https://private-user-images.githubusercontent.com/174457925/362698287-13806977-eb69-4811-be1d-9e45d4a9f6a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5NDkyMzUsIm5iZiI6MTcyNDk0ODkzNSwicGF0aCI6Ii8xNzQ0NTc5MjUvMzYyNjk4Mjg3LTEzODA2OTc3LWViNjktNDgxMS1iZTFkLTllNDVkNGE5ZjZhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQxNjI4NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmY5OWZhN2FhNWYwMDU5OWZlNTkxNDk1NDE2MmU4M2E1YWEzODhiZmE4MGMwZWExMWUzOGJkNDk0YzE5ODliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xwxe-voyBvv9I3Y4Ox3tSlbtbRl-CCIklJttU_Za3Q0)

Раньше надо это было добавлять вручную в build.gradle, с выпуском новой версии убрал это из инструкции.

**Comment by DNAGamesGit** [comment]
> > @Leonavichus Прошу подсказать еще https://ads.yandex.com/helpcenter/ru/dev/android/gdpr у яндекс медиации есть такое требование Нету ли в этом плагине функционала для запуска такого окна?
> 
> Здравствуйте, такого функционала в плагине нет.

благодарю за ответ. подскажите пожалуйста, не планируется ли реализация этого в рамках sdk?

и если нет, можете хотя бы примерно подсказать, куда копать чтобы добавить эту реализацию? писать код на kotlin/java и билдить, затем подключать отдельным "собственным" плагином показ этого окна в игре?

**Comment by Leonavichus** [comment]
Если хотите можете сделать pull request [сюда](https://github.com/noctisalamandra/godot-yandex-ads-android/blob/main/GodotAndroidYandexAds/src/main/java/com/darkmoonight/godotandroidyandexads/GodotAndroidYandexAds.java). Я посмотрю, проверю и обновлю плагин. Либо можете у себя это сделать.
Также это добавть могу я, но это будет не скоро.
