### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by andrew-jk-1** [noctisalamandra/godot-yandex-ads-android#19]
Здравствуйте! Сделал все по инструкции, при экспорте выдает ошибку:
![Снимок экрана 2024-10-11 194123](https://github.com/user-attachments/assets/9ec373ef-5130-4d43-a29b-888e9b37bf7c)
Я правильно понимаю что в файле "android/build/build.gradle" необходимо заменить
`compileOptions {
        sourceCompatibility versions.javaVersion
        targetCompatibility versions.javaVersion
}`
на
`compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
}`
?
 [Пустой Gotot4.3 Проект]
Проблема в моей Java версии?
![Снимок экрана 2024-10-11 210343](https://github.com/user-attachments/assets/4d6253da-fc4e-4519-8afb-f83247837f6f)

**Comment by andrew-jk-1** [comment]
Та же ошибка при попытке экспорта "example" проекта.

**Comment by andrew-jk-1** [comment]
Без этого Аддона отлично экспортит apk билды (релиз и дебаг)

**Comment by Leonavichus** [comment]
Здравствуйте, вы тестировали демо версию проекта с этим аддоном?

**Comment by andrew-jk-1** [comment]
> Здравствуйте, вы тестировали демо версию проекта с этим аддоном?

Да, я загружал и тестировал демо версию. Выдает ту же ошибку.
