### ISSUE TITLE
API KEY?

### ISSUE THREAD

**Issue by disanapa** [noctisalamandra/godot-yandex-ads-android#3]
API KEY?

**Comment by Leonavichus** [comment]
API KEY no need to specify

**Comment by disanapa** [comment]
Спасибо. Баннер показывает, а межстраничку и с вознаграждением не получается.

**Comment by Leonavichus** [comment]
Странно, у меня все работает, можете скинуть скрины как вы настраивали?

**Comment by disanapa** [comment]
Все работает.
