### ISSUE TITLE
GooglePlay отклоняет обновление из-за нарушения правил "Приложений для всей семьи"

### ISSUE THREAD

**Issue by unicorndk** [noctisalamandra/godot-yandex-ads-android#5]
Здравствуйте!
Столкнулся с такой проблемой. GooglePlay отклоняет обновление из-за нарушения правил "Приложений для всей семьи". Суть нарушения заключается в том, что SDK Яндекса в видео-рекламе иногда показывает блок без возможности закрыть объявление спустя 5 секунд (кнопка появляется в конце). Поддержка Яндекса ничем не помогла, поэтому пишу сюда. Возможно ли добавить в плагин настройку "Child Directed", как в плагине Admob? Возможно ли настроить блок через SDK?

![image](https://user-images.githubusercontent.com/74968361/229507595-e25d7d2f-031a-4e92-b0e3-d09ceea7c2b8.png)

**Comment by Leonavichus** [comment]
Здравствуйте, к сожалению, я ничем не смогу вам помочь. Мой плагин лишь связующее звено между Яндексом и Godot.
