### ISSUE TITLE
Черный экран вместо объявления

### ISSUE THREAD

**Issue by skittonik** [noctisalamandra/godot-yandex-ads-android#6]
Версия движка 3.5.2, пробовал разные версии плагина, итог один - черный экран с крестиком справа сверху при попытке вызвать Interstitial.

![image](https://github.com/DarkMooNight/godot-yandex-ads-android/assets/83069727/6cb1ee7c-d784-4745-b2d8-2449d2aa88bb)

**Comment by Leonavichus** [comment]
А можете скинуть скрин или рассказать как вы настраивали плагин, чтобы я мог понять в чем ошибка?

**Comment by skittonik** [comment]
> А можете скинуть скрин или рассказать как вы настраивали плагин, чтобы я мог понять в чем ошибка?

Я даже все повторил на пустом проекте Godot 3.5.2
[ads-test.zip](https://github.com/DarkMooNight/godot-yandex-ads-android/files/11511455/ads-test.zip)

Создал пустой проект;
Установил Android Build Template;
Скачал плагин: godot-3.5.2-yandex-ads;
Сделал все по инструкции;

Но тут еще момент вылез, если оставить com.yandex.android:mobileads:5.6.0 версию в bundle.gradle то игра даже не запустится, просто вылетит. Если 5.7.0 то запустится, но вместо рекламы черное окно.

Настройки экспорта:
![image](https://github.com/DarkMooNight/godot-yandex-ads-android/assets/83069727/1eac7542-43aa-4c41-9ecf-39b4e16305d2)

И еще, возможно, в Permissions нужно указывать "Internet", но все равно это ничего не дало.

**Comment by skittonik** [comment]
Может есть шаги или моменты что я не сделал?

**Comment by Leonavichus** [comment]
а какие атрибуты вы заполняли в скрипте?

**Comment by Leonavichus** [comment]
просто api key заполнять не надо, если вы его заполнили

**Comment by skittonik** [comment]
> а какие атрибуты вы заполняли в скрипте?

В каком именно скрипте? Можете посмотреть в проекте, что я скинул. Там чистый проект с двумя подключенными кнопками Interstitial и Rewarded.

**Comment by Leonavichus** [comment]
сейчас тогда включу ноутбук и посмотрю

**Comment by Leonavichus** [comment]
Да, у меня тоже Interstitial не работает, а Rewarded работает. Странно.

**Comment by skittonik** [comment]
> Да, у меня тоже Interstitial не работает, а Rewarded работает. Странно.

В Rewarded заглушка показывается, при клике открывается инструкция по Yandex SDK.

**Comment by Leonavichus** [comment]
Она и будет показываться, пока вы не активируете приложение.

**Comment by skittonik** [comment]
Приложение активировано в РСЯ. Но реклама все равно не работает, из нового - теперь выдает ошибку "2" после загрузки Interstitial.

**Comment by skittonik** [comment]
![image](https://github.com/DarkMooNight/godot-yandex-ads-android/assets/83069727/8abcaec5-cfc9-4034-bfa3-8aab834faf15)

**Comment by Leonavichus** [comment]
Я постараюсь решить эту проблему, но попозже.
