### ISSUE TITLE
google не обновляет приложение

### ISSUE THREAD

**Issue by disanapa** [noctisalamandra/godot-yandex-ads-android#7]
google не обновляет приложение, ссылается на SDK: com.yandex.android, собирает информацию о пользователях. Куда копать?

**Comment by Leonavichus** [comment]
Надо настроить блок безопасности в google play скорее всего.

**Comment by disanapa** [comment]
Там практически все перепробовал, не пойму что они подразумевают. Приложению уже пару лет, обновил sdk яндекса до 5.8.0, больше ничего не менял. 4 редакции отклонили.

**Comment by Leonavichus** [comment]
https://dzen.ru/media/id/5ea590115bba1914159d3e5d/kak-pravilno-zapolnit-razdel-bezopasnost-dannyh-v-google-play-console-62ef3fa95c713242a774a60c
В последний раз я делал как указанно в этой статье, но это было очень давно. Не знаю актуально ли это сейчас.

**Comment by disanapa** [comment]
> https://dzen.ru/media/id/5ea590115bba1914159d3e5d/kak-pravilno-zapolnit-razdel-bezopasnost-dannyh-v-google-play-console-62ef3fa95c713242a774a60c В последний раз я делал как указанно в этой статье, но это было очень давно. Не знаю актуально ли это сейчас.

Спасибо, отправил с изменениями.

**Comment by disanapa** [comment]
Все спасибо. Последние обновления приложения опубликованы.

**Comment by Leonavichus** [comment]
Не за что.
